import Farmacia.Conexao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Chivela
 */
public class Consult extends javax.swing.JFrame {

    /**
     * Creates new form FrmFornecedor
     */
    Conexao conexao = new Conexao();
    String sql, identrada;
    String id = conexao.Read();
    int controlo =1,comparar = 0;

    public Consult() {
        initComponents();
        adddata();
        SelecionarP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpesquisa = new javax.swing.JTable();
        fechamento = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Datavendas = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jInternalFrame3.setVisible(true);

        tbpesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbpesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "NOMECLATURA", "CATEGORIA", "PREÇO", "QUANTIDADE VENDIDA", "TOTAL", "DATA", "CLIENTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbpesquisa);

        fechamento.setText("Fechamento: 0.00");

        jButton2.setText("Imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        try {
            Datavendas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Datavendas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Datavendas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DatavendasFocusGained(evt);
            }
        });
        Datavendas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DatavendasKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addComponent(fechamento, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Datavendas, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton2))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechamento)
                    .addComponent(jButton2)
                    .addComponent(Datavendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("PRODUTO EM STOCK", jInternalFrame3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DatavendasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DatavendasFocusGained
        adddata();
    }//GEN-LAST:event_DatavendasFocusGained

    private void DatavendasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DatavendasKeyReleased
SelecionarP();
    }//GEN-LAST:event_DatavendasKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if ("    /  /  ".equalsIgnoreCase(Datavendas.getText())) {
            JOptionPane.showMessageDialog(null, "ADD A DATA PRIMEIRO");
        } else {
       
        sql = "SELECT cliente.nome as clnome, "
                + "produto.nome as nom,produto.preco,"
                + "produto.tipo_medicamento,saidas.qtdade,saidas.total,saidas.data,funcionario.nome as fnome FROM saidas join"
                + " produto  on saidas.producto_id = produto.id  && saidas.data='"+Datavendas.getText()+"' && saidas.funcionario_id='"+id+"' "
                + "join cliente on cliente.id=saidas.cliente_id join funcionario on funcionario.id='" + id+ "' "
                + " ORDER BY saidas.id DESC";
        
         try (PreparedStatement ps = (PreparedStatement) conexao.conectar().prepareStatement(sql);
                ResultSet rs = ps.executeQuery()) {
            JRResultSetDataSource dataSource = new JRResultSetDataSource(rs);
            JasperPrint jasperPrint = JasperFillManager.fillReport("C:\\FARMACIA\\relatorios\\diariav.jasper", new HashMap(),dataSource);
            JasperViewer jv = new JasperViewer(jasperPrint,false);
            jv.setVisible(true);
          

        } catch (Exception e) {
            e.printStackTrace();
        }
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new FrmItenVendaAdm().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Consult().setVisible(true);
                
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Datavendas;
    private javax.swing.JLabel fechamento;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbpesquisa;
    // End of variables declaration//GEN-END:variables

   

  
    
    private void SelecionarP() {
        Double fechament = 0.0;
        if ("    /  /  ".equalsIgnoreCase(Datavendas.getText())) {
            JOptionPane.showMessageDialog(null, "ADD A DATA PRIMEIRO");
        } else {
       
        sql = "SELECT cliente.nome as clnome, "
                + "produto.nome as nom,produto.preco,"
                + "produto.tipo_medicamento,saidas.qtdade,saidas.total,saidas.data,funcionario.nome as fnome FROM saidas join"
                + " produto  on saidas.producto_id = produto.id  && saidas.data='"+Datavendas.getText()+"' && saidas.funcionario_id='"+id+"' "
                + "join cliente on cliente.id=saidas.cliente_id join funcionario on funcionario.id='" + id+ "' "
                + " ORDER BY saidas.id DESC";
        DefaultTableModel dtm = (DefaultTableModel) tbpesquisa.getModel();
        if (dtm.getRowCount() != 0) {

            ((DefaultTableModel) tbpesquisa.getModel()).setNumRows(0);// serve para formatar a tualiza a tabela e vai repor as linhas que tiver dentro da tabela que esta no java
            tbpesquisa.updateUI();

        }
int i =1;
        try (PreparedStatement ps = (PreparedStatement) conexao.conectar().prepareStatement(sql);
                ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                fechament+=rs.getInt(6);
                Object[] recebeDado = {i++,rs.getString(2), rs.getString(4),
                    rs.getString(3),  rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(1)};
                dtm.addRow(recebeDado);

            }
            fechamento.setText("Fechamento: "+fechament+"0");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    }

    private void adddata() {
        
        Date agora = new Date();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyMMdd");
        String recebedata = simpleDateFormat.format(agora);
        Datavendas.setText(recebedata);
    }
}
