
import Farmacia.Conexao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author user
 */
public class Devolucao extends javax.swing.JFrame {
 Conexao conexao = new Conexao();
    FrmFarmacia1 farmacia = new FrmFarmacia1();
    String sql, idcliente="1", idproduto,qtdporVenda,idvenda;
     String id = conexao.Read();
    /**
     * Creates new form Devolucao
     */
    public Devolucao() {
        initComponents();
        buscardata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbprodutosvendido = new javax.swing.JTable();
        idmovimento = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Datavendas = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Fatura nº");

        tbprodutosvendido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tbprodutosvendido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Descrição", "Quantidade", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbprodutosvendido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbprodutosvendidoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbprodutosvendido);

        idmovimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        idmovimento.setToolTipText("digite o numero da fatura");
        idmovimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idmovimentoKeyReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DEVOLUÇÃO DO PRODUTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        try {
            Datavendas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Datavendas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Datavendas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DatavendasFocusGained(evt);
            }
        });
        Datavendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatavendasActionPerformed(evt);
            }
        });
        Datavendas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DatavendasKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(idmovimento, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(Datavendas, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idmovimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Datavendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbprodutosvendidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbprodutosvendidoMouseClicked

        TableModel model = tbprodutosvendido.getModel();
        //        idfornecedor = (String) model.getValueAt(tbprodutosvendido.getSelectedRow(), 0);
        idvenda=(String) model.getValueAt(tbprodutosvendido.getSelectedRow(), 0);
        String pro = (String) model.getValueAt(tbprodutosvendido.getSelectedRow(), 1);
        String qtd = (String) model.getValueAt(tbprodutosvendido.getSelectedRow(), 2);
        // moradafornecedor.setText((String) model.getValueAt(tbfornecedor.getSelectedRow(), 3));

        //desablitarcampo();
        // editarfornecedor.setEnabled(true);
        if (evt.getClickCount()==2){
            int confirmar = JOptionPane.showConfirmDialog(null, "DESEJA FAZER A DEVOLUÇÃO DO "+pro+" ", "ATENÇÃO", JOptionPane.YES_NO_OPTION);
            if (confirmar == JOptionPane.YES_OPTION) {

                atualizarapagar(idvenda,qtd);
                selecionar();
                //SelecionarP();

            }
        }

    }//GEN-LAST:event_tbprodutosvendidoMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
new FrmItenVenda().setVisible(true);
this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void idmovimentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idmovimentoKeyReleased
        selecionar();
    }//GEN-LAST:event_idmovimentoKeyReleased

    private void DatavendasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DatavendasFocusGained

        buscardata();
    }//GEN-LAST:event_DatavendasFocusGained

    private void DatavendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatavendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatavendasActionPerformed

    private void DatavendasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DatavendasKeyPressed

    }//GEN-LAST:event_DatavendasKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Devolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Devolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Devolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Devolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Devolucao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Datavendas;
    private javax.swing.JFormattedTextField idmovimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbprodutosvendido;
    // End of variables declaration//GEN-END:variables

    
    private void atualizarapagar(String idvenda,String qtd) {
        
        
        int recebeid=0,idpr=0;
        
        
        
         sql = "select producto_id from saidas where id ='" + idvenda + "' ORDER BY id desc LIMIT 1";

            try (PreparedStatement ps = (PreparedStatement) conexao.conectar().prepareStatement(sql);
                    ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    idpr = rs.getInt(1);
                    

                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        sql = "select id from entradas where producto_id ='" + idpr + "' ORDER BY caducidade desc LIMIT 1";

            try (PreparedStatement ps = (PreparedStatement) conexao.conectar().prepareStatement(sql);
                    ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    recebeid = rs.getInt(1);
                    

                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        
        
        sql = "update entradas set stock = stock+'" + qtd + "' where id = '" + recebeid + "'";

                try {
                    conexao.conectar();
                    conexao.cadastrar_dado(sql);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
        
         sql = "delete from saidas where id='" + idvenda + "' ";
         //sql = "update saidas set cliente_id = '0' where funcionario_id ='"+id+"' id = '" + idvenda + "'";

        try {
            conexao.conectar();
            int a = conexao.cadastrar_dado(sql);
            if (a != 0) {
                JOptionPane.showMessageDialog(null, "sucesso");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void buscardata() {
       
      Date agora = new Date();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyMMdd");
        String recebedata = simpleDateFormat.format(agora);
        Datavendas.setText(recebedata);  
        
    }
    private void selecionar() {
         sql = "SELECT "
                + "saidas.id,produto.nome, saidas.qtdade, saidas.total FROM saidas  inner join"
                + " produto  on saidas.producto_id = produto.id && saidas.cliente_id<>'0' && saidas.data= '"+Datavendas.getText()+"'  && saidas.idmovimento = '" + idmovimento.getText() + "' "
                + "ORDER BY saidas.id ASC";
        DefaultTableModel dtm = (DefaultTableModel) tbprodutosvendido.getModel();
        if (dtm.getRowCount() != 0) {

            ((DefaultTableModel) tbprodutosvendido.getModel()).setNumRows(0);// serve para formatar a tualiza a tabela e vai repor as linhas que tiver dentro da tabela que esta no java
            tbprodutosvendido.updateUI();

        }
        
        tbprodutosvendido.setAutoResizeMode(tbprodutosvendido.AUTO_RESIZE_OFF);
tbprodutosvendido.getColumnModel().getColumn(0).setPreferredWidth(34);
tbprodutosvendido.getColumnModel().getColumn(1).setPreferredWidth(300);
tbprodutosvendido.getColumnModel().getColumn(3).setPreferredWidth(100);
        try (PreparedStatement ps = (PreparedStatement) conexao.conectar().prepareStatement(sql);
                ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                Object[] recebeDado = {rs.getString(1),rs.getString(2), rs.getString(3), rs.getString(4)};
                dtm.addRow(recebeDado);
               // totalcompra += rs.getInt(4);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        //ValorTotalVenda.setText("" + totalcompra);
    }
}
