import Farmacia.Conexao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Chivela
 */
public class FrmFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form FrmFornecedor
     */
    Conexao conexao = new Conexao();
    String sql, idfuncionario;
    int comparar = 0;

    public FrmFuncionario() {
        initComponents();
                SelecionarM();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomefuncionario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        telefonefuncionario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        salvarfornecedor = new javax.swing.JButton();
        novofornecedor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbfuncionario = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        TXTPESQUISAR = new javax.swing.JTextField();
        editarfornecedor = new javax.swing.JButton();
        moradafuncioanrio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        funcaofuncionariio = new javax.swing.JComboBox();
        senhafuncionario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bifuncionario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        estadofuncionario = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        generofuncionario = new javax.swing.JComboBox();
        novofornecedor1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("NOME");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("TELEFONE");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("MORADA");

        salvarfornecedor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        salvarfornecedor.setText("SALVA");
        salvarfornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarfornecedorActionPerformed(evt);
            }
        });

        novofornecedor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        novofornecedor.setText("NOVO");
        novofornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novofornecedorActionPerformed(evt);
            }
        });

        tbfuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "NOME", "TELEFONE", "BI", "GENERO", "CARGO", "ESTADO", "SENHA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbfuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbfuncionarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbfuncionario);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("CADASTRO DOS FUNCIONARIOS");

        TXTPESQUISAR.setToolTipText("Busca");
        TXTPESQUISAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPESQUISARActionPerformed(evt);
            }
        });
        TXTPESQUISAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTPESQUISARKeyReleased(evt);
            }
        });

        editarfornecedor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        editarfornecedor.setText("EDITAR");
        editarfornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarfornecedorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("FUNÇÃO");

        funcaofuncionariio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        funcaofuncionariio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GERENTE", "FUNCIONARIO" }));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("ESTADO");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Nº BI");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("SENHA");

        estadofuncionario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        estadofuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NAO ACTIVO", "ACTIVO" }));
        estadofuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadofuncionarioActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("GENERO");

        generofuncionario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        generofuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MASCULINO", "FEMININO" }));
        generofuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generofuncionarioActionPerformed(evt);
            }
        });

        novofornecedor1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        novofornecedor1.setText("Pesquisar");
        novofornecedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novofornecedor1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(funcaofuncionariio, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(telefonefuncionario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomefuncionario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(moradafuncioanrio)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(salvarfornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(editarfornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(novofornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(74, 74, 74)
                            .addComponent(TXTPESQUISAR, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11)
                            .addComponent(novofornecedor1)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(senhafuncionario)
                    .addComponent(bifuncionario)
                    .addComponent(estadofuncionario, 0, 257, Short.MAX_VALUE)
                    .addComponent(generofuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomefuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(telefonefuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moradafuncioanrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generofuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estadofuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bifuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funcaofuncionariio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhafuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarfornecedor)
                    .addComponent(novofornecedor)
                    .addComponent(editarfornecedor)
                    .addComponent(TXTPESQUISAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(novofornecedor1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salvarfornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarfornecedorActionPerformed

        if (comparar == 0) {
            SalvarFuncionario();

        } else {
            AtualizarFuncionario();
            comparar = 0;
            salvarfornecedor.setText("SALVAR");
        }
        SelecionarM();
        desablitarcampo();

    }//GEN-LAST:event_salvarfornecedorActionPerformed

    private void novofornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novofornecedorActionPerformed
        LimparCampo();
        comparar = 0;
        salvarfornecedor.setText("SALVAR");
    }//GEN-LAST:event_novofornecedorActionPerformed

    private void TXTPESQUISARKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTPESQUISARKeyReleased
        SelecionarM();
    }//GEN-LAST:event_TXTPESQUISARKeyReleased

    private void tbfuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbfuncionarioMouseClicked

        TableModel model = tbfuncionario.getModel();
        
        idfuncionario = (String) model.getValueAt(tbfuncionario.getSelectedRow(), 0);
        nomefuncionario.setText((String) model.getValueAt(tbfuncionario.getSelectedRow(), 1));
        telefonefuncionario.setText((String) model.getValueAt(tbfuncionario.getSelectedRow(), 2));
        bifuncionario.setText((String) model.getValueAt(tbfuncionario.getSelectedRow(), 3));
        senhafuncionario.setText((String) model.getValueAt(tbfuncionario.getSelectedRow(), 7));
        funcaofuncionariio.setSelectedItem((String) model.getValueAt(tbfuncionario.getSelectedRow(), 5));
        generofuncionario.setSelectedItem((String) model.getValueAt(tbfuncionario.getSelectedRow(), 4));
        estadofuncionario.setSelectedItem((String) model.getValueAt(tbfuncionario.getSelectedRow(), 6));
        desablitarcampo();
        editarfornecedor.setEnabled(true);


    }//GEN-LAST:event_tbfuncionarioMouseClicked

    private void editarfornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarfornecedorActionPerformed
        salvarfornecedor.setEnabled(true);
        salvarfornecedor.setText("ATUALIZAR");
        comparar = 1;
        nomefuncionario.setEnabled(true);
        telefonefuncionario.setEnabled(true);
        moradafuncioanrio.setEnabled(true);
        funcaofuncionariio.setEnabled(true);
        generofuncionario.setEnabled(!false);
        estadofuncionario.setEnabled(!false);
        bifuncionario.setEnabled(true);
        senhafuncionario.setEnabled(true);

    }//GEN-LAST:event_editarfornecedorActionPerformed

    private void TXTPESQUISARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPESQUISARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPESQUISARActionPerformed

    private void estadofuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadofuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadofuncionarioActionPerformed

    private void generofuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generofuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generofuncionarioActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
          new FrmFarmacia1().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void novofornecedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novofornecedor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novofornecedor1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTPESQUISAR;
    private javax.swing.JTextField bifuncionario;
    private javax.swing.JButton editarfornecedor;
    private javax.swing.JComboBox estadofuncionario;
    private javax.swing.JComboBox funcaofuncionariio;
    private javax.swing.JComboBox generofuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField moradafuncioanrio;
    private javax.swing.JTextField nomefuncionario;
    private javax.swing.JButton novofornecedor;
    private javax.swing.JButton novofornecedor1;
    private javax.swing.JButton salvarfornecedor;
    private javax.swing.JTextField senhafuncionario;
    private javax.swing.JTable tbfuncionario;
    private javax.swing.JTextField telefonefuncionario;
    // End of variables declaration//GEN-END:variables

    private void SalvarFuncionario() {
        sql = "insert into funcionario values(null,'" + nomefuncionario.getText().toUpperCase() + "', "
                + "'" + telefonefuncionario.getText().toUpperCase() + "'"
                + ",'" + bifuncionario.getText().toUpperCase() + "','" + senhafuncionario.getText() + "'"
                + ", '" + moradafuncioanrio.getText().toUpperCase() + "',"
                + "'" + funcaofuncionariio.getSelectedItem() + "','" + generofuncionario.getSelectedItem() + "',"
                + " '" + estadofuncionario.getSelectedItem() + "')";

        try {
            conexao.conectar();
            int a = conexao.cadastrar_dado(sql);
            if (a != 0) {
                JOptionPane.showMessageDialog(null, "REGISTO CADASTRADO COM SUCESSO");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void AtualizarFuncionario() {

        sql = "update funcionario set nome = '" + nomefuncionario.getText().toUpperCase() + "'"
                + ", telefone ='" + telefonefuncionario.getText().toUpperCase() + "'"
                + ", bi ='" + bifuncionario.getText().toUpperCase() + "',"
                + " sexo ='" + generofuncionario.getSelectedItem() + "', "
                + "estado ='" + estadofuncionario.getSelectedItem() + "',senha ='" + senhafuncionario.getText() + "',"
                + "  cargo = '" + funcaofuncionariio.getSelectedItem() + "'  where id = '" + idfuncionario + "'";

        try {
            conexao.conectar();
            int verificar = conexao.cadastrar_dado(sql);
            if (verificar != 0) {
                JOptionPane.showMessageDialog(null, "REGISTO ATUALIZADO COM SUCESSO");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void LimparCampo() {

        nomefuncionario.setEnabled(true);
        telefonefuncionario.setEnabled(true);
        funcaofuncionariio.setEnabled(true);
        moradafuncioanrio.setEnabled(true);
        salvarfornecedor.setEnabled(true);
        novofornecedor.setEnabled(!true);
        editarfornecedor.setEnabled(!true);
        generofuncionario.setEnabled(!false);
        estadofuncionario.setEnabled(!false);
        bifuncionario.setEnabled(true);
        senhafuncionario.setEnabled(true);

        nomefuncionario.setText("");
        moradafuncioanrio.setText("");
        telefonefuncionario.setText("");
        funcaofuncionariio.setSelectedIndex(0);
        bifuncionario.setText("");
        senhafuncionario.setText("");
        generofuncionario.setSelectedIndex(0);
         estadofuncionario.setSelectedIndex(0);
         

    }

    private void desablitarcampo() {
        nomefuncionario.setEnabled(false);
        telefonefuncionario.setEnabled(false);
        funcaofuncionariio.setEnabled(false);
        generofuncionario.setEditable(false);
        estadofuncionario.setEditable(false);
        bifuncionario.setEnabled(false);
        senhafuncionario.setEnabled(false);
        moradafuncioanrio.setEnabled(!true);
        salvarfornecedor.setEnabled(false);
        editarfornecedor.setEnabled(false);
        novofornecedor.setEnabled(true);
        generofuncionario.setEnabled(false);
        estadofuncionario.setEnabled(false);
        bifuncionario.setEnabled(false);
        senhafuncionario.setEnabled(false);

    }

    private void SelecionarM() {
        sql = "select * from funcionario where nome like '" + TXTPESQUISAR.getText().toUpperCase() + "%' ORDER BY id desc";
        DefaultTableModel dtm = (DefaultTableModel) tbfuncionario.getModel();
        if (dtm.getRowCount() != 0) {

            ((DefaultTableModel) tbfuncionario.getModel()).setNumRows(0);// serve para formatar a tualiza a tabela e vai repor as linhas que tiver dentro da tabela que esta no java
            tbfuncionario.updateUI();

        }
        tbfuncionario.setAutoResizeMode(tbfuncionario.AUTO_RESIZE_OFF);
tbfuncionario.getColumnModel().getColumn(0).setPreferredWidth(34);
tbfuncionario.getColumnModel().getColumn(1).setPreferredWidth(200);
tbfuncionario.getColumnModel().getColumn(3).setPreferredWidth(110);
        try (PreparedStatement ps = (PreparedStatement) conexao.conectar().prepareStatement(sql);
                ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                Object[] recebeDado = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(8)
                , rs.getString(7), rs.getString(9), rs.getString(5)};
                dtm.addRow(recebeDado);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
